
const UserActionType={
    //SET_CURRENT_USER:'SET_CURRENT_USER',
    GOOGLE_SIGNIN_START:'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START:'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    SIGNIN_FAIL:'SIGNIN_FAIL',
    
};

export default UserActionType;