
const UserActionType={
    //SET_CURRENT_USER:'SET_CURRENT_USER',
    GOOGLE_SIGNIN_START:'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START:'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    SIGNIN_FAIL:'SIGNIN_FAIL',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNOUT_START:'SIGNOUT_START',
    SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
    SIGNOUT_FAIL:'SIGNOUT_FAIL',
    
};

export default UserActionType;